ALTER TABLE `oxarticles`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxcategories`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxcontents`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxmanufacturers`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxvendor`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';
