ALTER TABLE `oxarticles`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxarticles`
	ADD `IVOBA_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxarticles`
	ADD `IVOBA_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxarticles`
	ADD `IVOBA_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxcategories`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxcategories`
	ADD `IVOBA_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxcategories`
	ADD `IVOBA_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxcategories`
	ADD `IVOBA_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxcontents`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxcontents`
	ADD `IVOBA_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxcontents`
	ADD `IVOBA_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxcontents`
	ADD `IVOBA_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxmanufacturers`
	ADD `IVOBA_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxmanufacturers`
	ADD `IVOBA_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxmanufacturers`
	ADD `IVOBA_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '';
ALTER TABLE `oxmanufacturers`
	ADD `IVOBA_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';
